### ISSUE TITLE
Prepare jaxb2-maven-plugin to run on JDK 11

### ISSUE THREAD

**Issue by gunnarmorling** [mojohaus/jaxb2-maven-plugin#43]
Hi, when running the jaxb2-maven-plugin on JDK 9 I am getting quite a handful of errors due to the usage of classes previously present in tools.jar and now not exposed any longer.

I could make it work by adding the following dependencies to my plugin configuration:

```
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>codemodel</artifactId>
    <version>2.2.11</version>
</dependency>
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>txw2</artifactId>
    <version>2.2.11</version>
</dependency>
<dependency>
    <groupId>com.sun.xsom</groupId>
    <artifactId>xsom</artifactId>
    <version>20140925</version>
</dependency>
<dependency>
    <groupId>com.sun.istack</groupId>
    <version>2.21</version>
    <artifactId>istack-commons-runtime</artifactId>
</dependency>
<dependency>
    <groupId>com.sun.xml.bind.external</groupId>
    <artifactId>rngom</artifactId>
    <version>2.2.11</version>
</dependency>
```

I think the plug-in could be changed to always use these dependencies instead of relying on JDK-internal classes. Unfortunately, the POMs of these dependencies resolve to a non-existing variable ${tools}, so a warning about the POMs being invalid will be issued by mvn, but JAXB seems to work fine with them.

**Comment by lennartj** [comment]
At the moment, some plugins which we depend upon are not yet updated for Java9.

```
[ERROR] Failed to execute goal org.codehaus.mojo:cobertura-maven-plugin:2.7:clean (default) on project jaxb2-maven-plugin: Execution default of goal org.codehaus.mojo:cobertura-maven-plugin:2.7:clean failed: Plugin org.codehaus.mojo:cobertura-maven-plugin:2.7 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:0 at specified path /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/../lib/tools.jar -> [Help 1]
```

**Comment by ge0ffrey** [comment]
We're seeing a similar issue for Drools, when running a build, that works on JDK 8, on JDK 9: https://issues.jboss.org/browse/DROOLS-1170

**Comment by lennartj** [comment]
This is not an unimportant issue by any means. 
In its present form, the plugin will not be able to run on JDK9.

However, I am tempted to defer starting fixing it until this autumn to give 
other plugin developers the chance to make their plugins compliant with 
JDK9 before integrating the JDK9 support into the jaxb2-maven-plugin.

**Comment by ge0ffrey** [comment]
@lennartj A lot of high profile projects are now in full throttle in testing against JDK 9, as part of the "JDK 9 quality outreach" program started a few months ago. Here's a list of those projects:
  https://wiki.openjdk.java.net/display/quality/Quality+Outreach

That has been direct cause for us to start testing against JDK 9.
Download JDK 9 can be easily downloaded here: https://jdk9.java.net/download/

**Comment by gunnarmorling** [comment]
For now I'm not using the jaxb2-maven-plugin for my Java 9 experiments as I couldn't get it to work. For some reason it would ignore the JAXB binding file I need to use (and which always was applied when using the plug-in with JDK 8).

So I'm invoking _xjc_ explicitly now with some Maven trickery. I'm going to share it here, maybe it's helpful to others:

    
    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>1.4</version>
        <executions>
            <execution>
                <phase>generate-sources</phase>
                <configuration>
                    <tasks>
                        <echo message="Creating target/generated-sources/jaxb"/>
                        <mkdir dir="./target/generated-sources/jaxb"/>
                    </tasks>
                </configuration>
                <goals>
                    <goal>run</goal>
                </goals>
            </execution>
        </executions>
    </plugin>

    
    <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <executions>
            <execution>
                <id>generate schema types</id>
                <phase>generate-sources</phase>
                <goals>
                    <goal>exec</goal>
                </goals>
            </execution>
        </executions>
        <configuration>
            <executable>xjc</executable>
            <arguments>
                <argument>-enableIntrospection</argument>
                <argument>-p</argument>
                <argument>org.hibernate.validator.internal.xml</argument>
                <argument>-extension</argument>
                <argument>-target</argument>
                <argument>2.1</argument>
                <argument>-d</argument>
                <argument>target/generated-sources/jaxb</argument>
                <argument>src/main/xsd/validation-configuration-1.1.xsd</argument>
                <argument>src/main/xsd/validation-mapping-1.1.xsd</argument>
                <argument>-b</argument>
                <argument>src/main/xjb/binding-customization.xjb</argument>
            </arguments>
        </configuration>
    </plugin>

    
    <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
            <execution>
                <id>add-source</id>
                <phase>generate-sources</phase>
                <goals>
                    <goal>add-source</goal>
                </goals>
                <configuration>
                    <sources>
                        <source>target/generated-sources/jaxb</source>
                    </sources>
                </configuration>
            </execution>
        </executions>
    </plugin>

**Comment by lennartj** [comment]
I am quite aware of this; although we will include support for JDK9 within the plugin I will start with a much-needed release (2.3) handling enums, enhanced schema generation and various other fixes.

After that, we should approach 2 things:

1. Supporting Java 9, and
1. See if we can merge the codebases for the two JAXB plugins (i.e. this one and the one from java.net).  While this latter task is certainly optional, I believe it would be good to have 1 "semi-normative" JAXB plugin rather than two which works in different ways. However, this is not only up to me and the rest of the MojoHaus folks, but also Alexei and the committers at java.net.

**Comment by lennartj** [comment]
And also - Thanks @gunnarmorling for sharing the Exec-plugin recipe.

**Comment by lennartj** [comment]
For the 2.4 version of the plugin (or perhaps we should move to 3.0 for this feature), we should support JDK 9.

**Comment by eolivelli** [comment]
I am getting this error with 2.3.1 version:

> [ERROR] Failed to execute goal org.codehaus.mojo:jaxb2-maven-plugin:2.3.1:xjc (xjc) on project magnews.uiapp.testcase: Execution xjc of goal org.codehaus.mojo:jaxb2-maven-plugin:2.3.1:xjc failed: A required class was missing while executing org.codehaus.mojo:jaxb2-maven-plugin:2.3.1:xjc: com/sun/codemodel/CodeWriter

Any plan to fix this issue ? is there a schedule for 2.4 ?
I will be glad to help if needed for me it is a showstopper for the migration to Java9

**Comment by lennartj** [comment]
There are clear plans to fix it.
However, the tools.jar and JDK organisation to some extent is revamped in JDK 9.

... so this issue requires a tad more attention to detail than usual, to enable the plugin to run both on JDK8 and earlier and (using the same codebase) JDK9

**Comment by eolivelli** [comment]
thank you @lennartj for your quick reply.

I see your point, I will wait.
I will test the new version as soon the fix will be available

**Comment by gunnarmorling** [comment]
> enable the plugin to run both on JDK8 and earlier and (using the same codebase) JDK9

On that specific one, it may be a good idea to produce a multi-release JAR, allowing to have different versions of specific classes, each tied to one Java version. I've blogged about [building MR JARs](http://in.relation.to/2017/02/13/building-multi-release-jars-with-maven/) recently.

**Comment by Novanic** [comment]
The workaround with exec-maven-plugin is not working in my (current) environment, it throws: "A type incompatibility occurred while executing org.codehaus.mojo:exec-maven-plugin:1.6.0:exec: java.base/java.lang.String cannot be cast to org.codehaus.mojo.exec.Modulepath"... And jaxb2-maven-plugin is still not runnable with Java 9 (it uses classes which are moved to an internal package, so it is not even possible to just open the visibility...). You have 2,5 months at maximum to get this working. ;-)

**Comment by rfscholte** [comment]
https://stackoverflow.com/questions/46356092/jaxb2-maven-plugin-failing-on-java-9 is a good hint. For these java.se.ee modules we should find the matching dependency in Central. Most should be there, and it will also work with earlier java version(s).

**Comment by subes** [comment]
I fixed this issue by launched `com.sun.tools.xjc.XJCFacade` from a forked java process (because the facade calls System.exit -_-) inside my own plugin instead of continuing to scratch my head about why jaxb2-maven-plugin does not use .xjb schema bindings with java 9. At least this approach seems to be more robust regarding future java versions. Also this approach does not rely on the xjc executable being in the $PATH. I made this downwards compatible by using the approach from [here](https://github.com/olivergondza/maven-jdk-tools-wrapper/) to declare java version dependant dependencies. You can see the result here: 
- https://github.com/subes/invesdwin-maven-plugin/blob/master/invesdwin-maven-plugin-parent/pom.xml
- https://github.com/subes/invesdwin-maven-plugin/blob/master/invesdwin-maven-plugin-parent/invesdwin-maven-plugin/src/main/java/de/invesdwin/maven/plugin/GenerateSourcesMojo.java

Maybe this helps in finding a solution for jaxb2-maven-plugin that is downwards compatible.

**Comment by Heterodyne** [comment]
Is there progress in resolving this problem when using Java 9 ?

`[ERROR] Failed to execute goal org.codehaus.mojo:jaxb2-maven-plugin:2.3.1:xjc (xjc) on project magnews.uiapp.testcase: Execution xjc of goal org.codehaus.mojo:jaxb2-maven-plugin:2.3.1:xjc failed: A required class was missing while executing org.codehaus.mojo:jaxb2-maven-plugin:2.3.1:xjc: com/sun/codemodel/CodeWriter`

**Comment by dlemmermann** [comment]
Any news on this?

**Comment by lennartj** [comment]
Will start the development transition from the Maven2 compliant plugin to the Maven3 (and Java9) compliant plugin next week.

**Comment by lennartj** [comment]
Currently, there are a few plugins and/or code quality dependencies which are not Java 9 compliant.

Among those are Cobertura and Checkstyle.
Will investigate if we can ensure plugin code quality without such plugins... or when they - in turn - expect to be Java 9 compliant.

**Comment by ptahchiev** [comment]
Java10 on the horizon, you guys still lack support for Java9 :(

**Comment by jvissers** [comment]
FYI: Found that http://cxf.apache.org/cxf-xjc-plugin.html (version 3.2.1) - does honor schemaBindings correctly. So these guys apparently have fixed the issue ~ which they also ran into.

**Comment by PascalSchumacher** [comment]
A fix for this would be highly appreciated!

By the way: Thank you very much for providing the maven-jaxb2-plugin! 👍

**Comment by tuxedo0801** [comment]
Any update on this?

**Comment by martinjoconnor** [comment]
Also keenly awaiting an update.

**Comment by lennartj** [comment]
Now that release 2.4 is performed, the task of morphing the plugin for compliance with java 9, 10 and 11 is started.

The main problem is the dependency on the tools.jar (which is removed in Java9) for the compilation part of the plugin. While `toolchains` is a great way of injecting relevant parts of the JDK to plugins, tools.jar is not present within java 9+. Investigating the best alternative approach.

**Comment by lennartj** [comment]
However, the invoker plugin executes the failsafe plugin, which would need to add these options within a profile for java 9+.

... and I find it somewhat unclear to derive the optimal pattern for the corresponding module ... which is the `java.activation` module.

**Comment by eolivelli** [comment]
From java9 onwards you have to explicitly add JAXB, Java Activation...dependency


```
<libs.jaxws.jaxb-api>2.3.0</libs.jaxws.jaxb-api>
<libs.jaxws.jaxb-impl>2.3.0</libs.jaxws.jaxb-impl>
<libs.javaxactivation.api>1.2.0</libs.javaxactivation.api>

```

and these are the deps:

```
         <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>${libs.jaxws.jaxb-api}</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <version>${libs.jaxws.jaxb-impl}</version>
        </dependency>
        <dependency>
            <groupId>javax.activation</groupId>
            <artifactId>javax.activation-api</artifactId>
            <version>${libs.javaxactivation.api}</version>
        </dependency>
        <dependency>
            <groupId>com.sun.activation</groupId>
            <artifactId>javax.activation</artifactId>
            <version>${libs.javaxactivation.api}</version>
        </dependency>
```

And consider upgrading surefire to the latest version, which has some fixes for jdk9/jdk10

Hope that helps

**Comment by lennartj** [comment]
But the problem arises from the Maven Invoker Plugin which fires the Failsafe plugin under the hood.

Also - the integration tests will need to work under both JDK 7,8,9 and 10.
Still working on this.

**Comment by martinjoconnor** [comment]
Any update on this?

We recently migrated our system to Java 10 but have one component still requiring Java 8 because of its dependence on this (excellent) plugin.

**Comment by lennartj** [comment]
The problem - currently - is related to the schemagen tool. When running the integration tests for the plugin, I get failures when running JDK 9, 10, and 11. The reason is that schemagen behaves differently from when run under JDK 8.

````
JDK 1.8 execution:
==================
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" targetNamespace="http://acme.com/customer-api" xmlns:tns="http://acme.com/customer-api" xmlns:xs="http://www.w3.org/2001/XMLSchema">
````

... but ... 

````
JDK 9 execution:
================
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<schema version="1.0" targetNamespace="http://acme.com/customer-api" xmlns:tns="http://acme.com/customer-api" xmlns:xs="http://www.w3.org/2001/XMLSchema">
````

Notice that the namespace prefix of the `schema` element is missing from the JDK9 execution?
This seems incorrect, and implies that the schema/root element is `http://acme.com/customer-api` instead of `http://www.w3.org/2001/XMLSchema`, which it should be. 

As far as I can tell, this is another `schemagen` internal behavior change from JDK 8 to 9. I cannot seem to find any workaround to change this behavior. Due to the namespace being incorrect, the transformation steps will not apply their magic - because the plugin expects the schema element to reside in its proper namespace.

**Comment by lennartj** [comment]
So .. we need to report this as a bug against the `schemagen` tool in JDK 9 and 10.
`schemagen` is altogether removed from JDK 11 - so we will hence need to re-implement the internals of this plugin to enable it running on top of JDK 11.

**Comment by agusmba** [comment]
Yes. I'm not sure if it's the same one as https://github.com/eclipse-ee4j/jaxb-ri/issues/1220 or if a new one should be opened.

Regarding the removal from JDK11, this can shed some light on how to integrate it:
https://github.com/eclipse-ee4j/jaxb-ri/issues/1168#issuecomment-395753567

(Note: I've put the links to the new repository)

**Comment by lennartj** [comment]
Thanks!  

I will take a look at the jaxb-ri project codebase to understand how to move on from here.
I want to avoid "manually" inserting the "xs:" prefix within the top schema element, and all relevant child elements within the generated schema.

**Comment by mw84367** [comment]
> Also, if you get the error `prefix '' is already bound to ''`, try disabling the `episode` file generation in xjc since it is turned on by default in jaxb2-maven-plugin as it seems.

This does no longer work since version 2.4, because the option is deprecated and thus ignored.

So how can this issue be fixed?

**Comment by RickDeckard76** [comment]
Hi, I confirm version 2.4 doesn't work with jdk11. Not possible for us to completly migrate to JDK11 until a fix will be release. Any news?

**Comment by anupamnayak** [comment]
> For now I'm not using the jaxb2-maven-plugin for my Java 9 experiments as I couldn't get it to work. For some reason it would ignore the JAXB binding file I need to use (and which always was applied when using the plug-in with JDK 8).
> 
> So I'm invoking _xjc_ explicitly now with some Maven trickery. I'm going to share it here, maybe it's helpful to others:
> 
> ```
> 
> <plugin>
>     <groupId>org.apache.maven.plugins</groupId>
>     <artifactId>maven-antrun-plugin</artifactId>
>     <version>1.4</version>
>     <executions>
>         <execution>
>             <phase>generate-sources</phase>
>             <configuration>
>                 <tasks>
>                     <echo message="Creating target/generated-sources/jaxb"/>
>                     <mkdir dir="./target/generated-sources/jaxb"/>
>                 </tasks>
>             </configuration>
>             <goals>
>                 <goal>run</goal>
>             </goals>
>         </execution>
>     </executions>
> </plugin>
> 
> 
> <plugin>
>     <groupId>org.codehaus.mojo</groupId>
>     <artifactId>exec-maven-plugin</artifactId>
>     <executions>
>         <execution>
>             <id>generate schema types</id>
>             <phase>generate-sources</phase>
>             <goals>
>                 <goal>exec</goal>
>             </goals>
>         </execution>
>     </executions>
>     <configuration>
>         <executable>xjc</executable>
>         <arguments>
>             <argument>-enableIntrospection</argument>
>             <argument>-p</argument>
>             <argument>org.hibernate.validator.internal.xml</argument>
>             <argument>-extension</argument>
>             <argument>-target</argument>
>             <argument>2.1</argument>
>             <argument>-d</argument>
>             <argument>target/generated-sources/jaxb</argument>
>             <argument>src/main/xsd/validation-configuration-1.1.xsd</argument>
>             <argument>src/main/xsd/validation-mapping-1.1.xsd</argument>
>             <argument>-b</argument>
>             <argument>src/main/xjb/binding-customization.xjb</argument>
>         </arguments>
>     </configuration>
> </plugin>
> 
> 
> <plugin>
>     <groupId>org.codehaus.mojo</groupId>
>     <artifactId>build-helper-maven-plugin</artifactId>
>     <executions>
>         <execution>
>             <id>add-source</id>
>             <phase>generate-sources</phase>
>             <goals>
>                 <goal>add-source</goal>
>             </goals>
>             <configuration>
>                 <sources>
>                     <source>target/generated-sources/jaxb</source>
>                 </sources>
>             </configuration>
>         </execution>
>     </executions>
> </plugin>
> ```

I am able to generated classes using this. But i have multiple xsd files and I want to generate classes in different packages! So i just used plugin multiple time. So problem I'm facing is that generated-sources folder getting cleared each time erasing old generated classes. 

There was aption in jaxb2 maven plugin to disable clearOutputDirectory. But Im not finding this over using exec maven plugin. 

Please can anyone help?

**Comment by dvsanthosh** [comment]
@lennartj , Can you please prioritize this issue. Seems like several folks are stuck with this issue.



> Hi, I confirm version 2.4 doesn't work with jdk11. Not possible for us to completly migrate to JDK11 until a fix will be release. Any news?

**Comment by lennartj** [comment]
See the explanations above.

The plugin suffers from bugs introduced in schemagen tool (i.e. JDK) for JDK 9+
This is a JDK - not plugin - bug which must be fixed in the JDK.

**Comment by RickDeckard76** [comment]
Hi Lennart, thx for your excellent work.
Ok, I understand about your consideration that this is a JDK 9/10/11 bug; JDK11 is a LTS, do you have some rumors about the resolution of the bug? On the other side, you wrote:
"I will take a look at the jaxb-ri project codebase to understand how to move on from here.
I want to avoid "manually" inserting the "xs:" prefix within the top schema element, and all relevant child elements within the generated schema."
Any news?
Thx in advance.

**Comment by dvsanthosh** [comment]
@lennartj Maybe I'm missing something here. As per the jdk11 release notes,schemagen and xjc (from jdk.xml.bind) have been removed and the openjdk community provided alternatives to this package. Do you mean these APIs too are having bugs in it?
Ref: 
https://openjdk.java.net/jeps/320
https://stackoverflow.com/questions/48204141/replacements-for-deprecated-jpms-modules-with-java-ee-apis/48204154#48204154

**Comment by boukewoudstra** [comment]
The xjc command util is missing in java11. However, this util just forwards any commands to the XJCFacade class from the jaxb-xjc package.

I did some experiments to use this class directly. That seems possible. See for my experiment: https://github.com/boukewoudstra/jaxb-xjc-java11-test. Maybe it can be used as inspiration to get this working again ;)

I am using the jaxb version 2.3.1. Version 2.3.0 was still giving reflection errors.

**Comment by missedone** [comment]
with regards to the issue of missing `xs:` prefix with goal `schemagen` running in Java 11, the workaround is building plexus-classworlds 2.5.3-SNAPSHOT, see  
https://github.com/eclipse-ee4j/jaxb-ri/issues/1220#issuecomment-449831200

here is my plugin dependency for your reference:
```xml
        <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>jaxb2-maven-plugin</artifactId>
            <dependencies>
                <dependency>
                    <groupId>org.glassfish.jaxb</groupId>
                    <artifactId>jaxb-jxc</artifactId>
                    <version>2.3.1</version>
                </dependency>
                <dependency>
                    <groupId>javax.activation</groupId>
                    <artifactId>javax.activation-api</artifactId>
                    <version>1.2.0</version>
                </dependency>
                <dependency>
                    <groupId>javax.xml.bind</groupId>
                    <artifactId>jaxb-api</artifactId>
                    <version>2.3.1</version>
                </dependency>
                <dependency>
                    <groupId>org.glassfish.jaxb</groupId>
                    <artifactId>jaxb-runtime</artifactId>
                    <version>2.3.1</version>
                </dependency>
            </dependencies>
            <executions>
                <execution>
                    <id>schemagen</id>
                    <phase>process-classes</phase>
                    <goals>
                        <goal>schemagen</goal>
                    </goals>
                </execution>
            </executions>
...
``

**Comment by lennartj** [comment]
I will take a look at the classworlds upgrade; from the comments, it looks promising.
... which implies that we only have to wait for a stable release of plexus-classworlds - but that should be a quicker process than the corresponding JDK release process.

**Comment by slachiewicz** [comment]
While waiting for Maven release - try with replacing plexus-classworld in local Maven install with the new version (2.6.0) from http://central.maven.org/maven2/org/codehaus/plexus/plexus-classworlds/2.6.0/

**Comment by berardino** [comment]
> For now I'm not using the jaxb2-maven-plugin for my Java 9 experiments as I couldn't get it to work. For some reason it would ignore the JAXB binding file I need to use (and which always was applied when using the plug-in with JDK 8).
> 
> So I'm invoking _xjc_ explicitly now with some Maven trickery. I'm going to share it here, maybe it's helpful to others:
> 
> ```
> 
> <plugin>
>     <groupId>org.apache.maven.plugins</groupId>
>     <artifactId>maven-antrun-plugin</artifactId>
>     <version>1.4</version>
>     <executions>
>         <execution>
>             <phase>generate-sources</phase>
>             <configuration>
>                 <tasks>
>                     <echo message="Creating target/generated-sources/jaxb"/>
>                     <mkdir dir="./target/generated-sources/jaxb"/>
>                 </tasks>
>             </configuration>
>             <goals>
>                 <goal>run</goal>
>             </goals>
>         </execution>
>     </executions>
> </plugin>
> 
> 
> <plugin>
>     <groupId>org.codehaus.mojo</groupId>
>     <artifactId>exec-maven-plugin</artifactId>
>     <executions>
>         <execution>
>             <id>generate schema types</id>
>             <phase>generate-sources</phase>
>             <goals>
>                 <goal>exec</goal>
>             </goals>
>         </execution>
>     </executions>
>     <configuration>
>         <executable>xjc</executable>
>         <arguments>
>             <argument>-enableIntrospection</argument>
>             <argument>-p</argument>
>             <argument>org.hibernate.validator.internal.xml</argument>
>             <argument>-extension</argument>
>             <argument>-target</argument>
>             <argument>2.1</argument>
>             <argument>-d</argument>
>             <argument>target/generated-sources/jaxb</argument>
>             <argument>src/main/xsd/validation-configuration-1.1.xsd</argument>
>             <argument>src/main/xsd/validation-mapping-1.1.xsd</argument>
>             <argument>-b</argument>
>             <argument>src/main/xjb/binding-customization.xjb</argument>
>         </arguments>
>     </configuration>
> </plugin>
> 
> 
> <plugin>
>     <groupId>org.codehaus.mojo</groupId>
>     <artifactId>build-helper-maven-plugin</artifactId>
>     <executions>
>         <execution>
>             <id>add-source</id>
>             <phase>generate-sources</phase>
>             <goals>
>                 <goal>add-source</goal>
>             </goals>
>             <configuration>
>                 <sources>
>                     <source>target/generated-sources/jaxb</source>
>                 </sources>
>             </configuration>
>         </execution>
>     </executions>
> </plugin>
> ```

the following also work : 

```xml
<properties>
        <exec-maven-plugin.version>1.6.0</exec-maven-plugin.version>
        <jaxb-xjc.version>2.3.1</jaxb-xjc.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>${exec-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <phase>none</phase>
                        <goals>
                            <goal>java</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <includePluginDependencies>true</includePluginDependencies>
                    <mainClass>com.sun.tools.xjc.XJCFacade</mainClass>
                    <arguments>
                        <argument>-d</argument>
                        <argument>${project.build.sourceDirectory}</argument>
                        <argument>${project.basedir}/xsd</argument>
                    </arguments>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.glassfish.jaxb</groupId>
                        <artifactId>jaxb-xjc</artifactId>
                        <version>${jaxb-xjc.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
```

**Comment by Heterodyne** [comment]
The other thing to note of course is that xjc has been removed from the jdk.xml.bind module.
It is now a standalone zip bundle...
[https://mvnrepository.com/artifact/com.sun.xml.bind/jaxb-ri/2.4.0-b180830.0438]

Perhaps this to should be added to the pom as a dependency..
`
<dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-ri</artifactId>
    <version>2.4.0-b180830.0438</version>
    <type>pom</type>
</dependency>
`

**Comment by davidmoten** [comment]
plexus-classworlds 2.6.0 didn't work for me with Java 9, perhaps I'm using it incorrectly (though I'm generating from DTD not xsd):

```xml
    <profile>
        <id>j9</id>
        <activation>
            <jdk>[1.9,)</jdk>
        </activation>
        <build>
            <plugins>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>jaxb2-maven-plugin</artifactId>
                    <version>2.4</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>xjc</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <!-- Set the package of the generated code -->
                        <packageName>au.gov.amsa.jul.jaxb</packageName>

                        <!-- Indicate that we should use DTD input instead 
                            of XSDs -->
                        <sourceType>dtd</sourceType>

                        <!-- Define the directory where we should find the 
                            DTD files -->
                        <sources>
                            <source>src/main/resources</source>
                        </sources>

                        <externalEntityProcessing>true</externalEntityProcessing>
                    </configuration>
                    <dependencies>
                        <dependency>
                            <groupId>org.codehaus.plexus</groupId>
                            <artifactId>plexus-classworlds</artifactId>
                            <version>2.6.0</version>
                        </dependency>
                        <dependency>
                            <groupId>com.sun.activation</groupId>
                            <artifactId>javax.activation</artifactId>
                            <version>1.2.0</version>
                        </dependency>
                    </dependencies>
                </plugin>
            </plugins>
        </build>
    </profile>
```

Output:
```
Failed to execute goal org.codehaus.mojo:jaxb2-maven-plugin:2.4:xjc (default) on project logging-jaxb: Prefix '' is already bound to '' -> [Help 1]
```

**Comment by missedone** [comment]
@davidmoten
You need to place the classworlds jar to $maven-home/boot rather than maven dependency 
Remember to delete or move the old jar

**Comment by davidmoten** [comment]
>@davidmoten
You need to place the classworlds jar to $maven-home/boot rather than maven dependency
Remember to delete or move the old jar

Thanks @missedone. If that's the case I won't even try it because I want our build to work everywhere not just on a patched maven installation. I'll try the exec:exec workaround from @anupamnayak now.

**Comment by davidmoten** [comment]
Ah, the `exec:exec` workaround from @gunnarmorling won't work from Java 11+ because `xjc` executable has been removed. I might make a simple *xjc-maven-plugin* using @subes work as basis (unfortunately his  binary is not deployed to Maven Central and I might make some simplifications to get it out there).

**Comment by subes** [comment]
@chrlembeck I think you can just change the system property file.encoding and xjc will pick it up:

https://stackoverflow.com/questions/361975/setting-the-default-java-character-encoding

Maybe you can do this inside your pom.xml otherwise a configuration option needs to be added to the plugin.

**Comment by chrlembeck** [comment]
@subes, @davidmoten: I tried both: Adding `<file.encoding>UTF-8</file.encoding>` into the properties section of the pom.xml and setting the system properties via `mvn -Dfile.encoding=UTF-8 clean compile`.
Unfortunately the was no effect and the generated source files can not be compiled because of its wrong encoding.

**Comment by subes** [comment]
Ok, it seems XJC has an option to set the encoding: https://docs.oracle.com/javase/9/tools/xjc.htm#JSWOR741

> "-encoding encoding" This option specifies character encoding for generated source files.

So using a configuration option and passing this as the parameter should solve the issue. Or maybe just pass the file.encoding property value as the option.

**Comment by edwardxia** [comment]
I got the current version of this plugin working on JDK 8, 9, 10, 11 just by explicitly declaring all the necessary dependencies:

``` xml
  <dependencies>
    <dependency>
      <groupId>org.glassfish.jaxb</groupId>
      <artifactId>jaxb-runtime</artifactId>
      <version>2.3.2</version>
    </dependency>
    <dependency>
      <groupId>com.sun.activation</groupId>
      <artifactId>jakarta.activation</artifactId>
      <version>1.2.1</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>jaxb2-maven-plugin</artifactId>
        <version>2.4</version>
        <executions>
          <execution>
            <id>xjc</id>
            <goals>
              <goal>xjc</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <packageName>......</packageName>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-xjc</artifactId>
            <version>2.3.2</version>
          </dependency>
          <dependency>
            <groupId>com.sun.activation</groupId>
            <artifactId>jakarta.activation</artifactId>
            <version>1.2.1</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>
```

**Comment by RickDeckard76** [comment]
> I got the current version of this plugin working on JDK 8, 9, 10, 11 just by explicitly declaring all the necessary dependencies:
> 
> ```
>   <dependencies>
>     <dependency>
>       <groupId>org.glassfish.jaxb</groupId>
>       <artifactId>jaxb-runtime</artifactId>
>       <version>2.3.2</version>
>     </dependency>
>     <dependency>
>       <groupId>com.sun.activation</groupId>
>       <artifactId>jakarta.activation</artifactId>
>       <version>1.2.1</version>
>     </dependency>
>   </dependencies>
> 
>   <build>
>     <plugins>
>       <plugin>
>         <groupId>org.codehaus.mojo</groupId>
>         <artifactId>jaxb2-maven-plugin</artifactId>
>         <version>2.4</version>
>         <executions>
>           <execution>
>             <id>xjc</id>
>             <goals>
>               <goal>xjc</goal>
>             </goals>
>           </execution>
>         </executions>
>         <configuration>
>           <packageName>......</packageName>
>         </configuration>
>         <dependencies>
>           <dependency>
>             <groupId>org.glassfish.jaxb</groupId>
>             <artifactId>jaxb-xjc</artifactId>
>             <version>2.3.2</version>
>           </dependency>
>           <dependency>
>             <groupId>com.sun.activation</groupId>
>             <artifactId>jakarta.activation</artifactId>
>             <version>1.2.1</version>
>           </dependency>
>         </dependencies>
>       </plugin>
>     </plugins>
>   </build>
> ```

Doesn't work for me.
Error is still: 

"[ERROR] Failed to execute goal org.codehaus.mojo:jaxb2-maven-plugin:2.4:xjc (XJC Build) on project test-backend: Prefix '' is already bound to '' -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:jaxb2-maven-plugin:2.4:xjc (XJC Build) on project test-backend: Prefix '' is already bound to ''

**Comment by RickDeckard76** [comment]
Hi all, I got the solution thanks to the excellent work of @davidmoten .
For all that are in my same situation (switching to JDK11 having few few time): simply go to the github page of @davidmoten here https://github.com/davidmoten/xjc-maven-plugin and use the plugin; it works without problems in my case.

**Comment by davidmoten** [comment]
Glad to hear it's working @RickDeckard76, I've migrated the *xjc-maven-plugin* code to a more generic plugin [jax-maven-plugin](https://github.com/davidmoten/jax-maven-plugin) that supports `xjc`, `wsimport`, `wsgen` and `schemagen` goals. I believe Rick used *jax-maven-plugin* successfully and I've applied it to a number of uses across my company codebase with success. I'd like to pick up more test cases to cover the problems mentioned in this thread so feel free to mention them on issues at *jax-maven-plugin*. By the way *jax-maven-plugin* is deployed to Maven Central.

**Comment by RickDeckard76** [comment]
> I confirm that @edwardxia solution works for OpenJDK 10. (After 4 hours looking everywhere... I finally got it working on java 10.
> 
> Hope it will works for 11 when we migrate to 11 :/

I confirm, it works on JDK11 (I used openJDK11 and Adopt-openJDK11)

**Comment by k-tomaszewski** [comment]
For me the solution provided by @edwardxia didn't work without adding a special workaround - I needed to put an extra, dummy XSD file to get rid of the error:
`[ERROR] Failed to execute goal org.codehaus.mojo:jaxb2-maven-plugin:2.4:xjc (xjc) on project test-project: Prefix '' is already bound to ''`

I've described the full solution here: https://artofcode.wordpress.com/2019/02/26/jaxb2-maven-plugin-2-4-and-java-11/

**Comment by charegre** [comment]
> I got the current version of this plugin working on JDK 8, 9, 10, 11 just by explicitly declaring all the necessary dependencies:
> 
> ```
>   <dependencies>
>     <dependency>
>       <groupId>org.glassfish.jaxb</groupId>
>       <artifactId>jaxb-runtime</artifactId>
>       <version>2.3.2</version>
>     </dependency>
>     <dependency>
>       <groupId>com.sun.activation</groupId>
>       <artifactId>jakarta.activation</artifactId>
>       <version>1.2.1</version>
>     </dependency>
>   </dependencies>
> 
>   <build>
>     <plugins>
>       <plugin>
>         <groupId>org.codehaus.mojo</groupId>
>         <artifactId>jaxb2-maven-plugin</artifactId>
>         <version>2.4</version>
>         <executions>
>           <execution>
>             <id>xjc</id>
>             <goals>
>               <goal>xjc</goal>
>             </goals>
>           </execution>
>         </executions>
>         <configuration>
>           <packageName>......</packageName>
>         </configuration>
>         <dependencies>
>           <dependency>
>             <groupId>org.glassfish.jaxb</groupId>
>             <artifactId>jaxb-xjc</artifactId>
>             <version>2.3.2</version>
>           </dependency>
>           <dependency>
>             <groupId>com.sun.activation</groupId>
>             <artifactId>jakarta.activation</artifactId>
>             <version>1.2.1</version>
>           </dependency>
>         </dependencies>
>       </plugin>
>     </plugins>
>   </build>
> ```

Hi,

I am using OpenJDK 11.0.2 and I tried your approach but I am getting the following error:

org.xml.sax.SAXParseException: External parsing is disabled. Cannot parse URI: file:/Path_to_my/my.dtd
at com.sun.xml.dtdparser.InputEntity.fatal (InputEntity.java:971)
    at com.sun.xml.dtdparser.InputEntity.init (InputEntity.java:140)
    at com.sun.xml.dtdparser.DTDParser.parseInternal (DTDParser.java:288)
...
...
[ERROR] Failed to execute goal org.codehaus.mojo:jaxb2-maven-plugin:2.4:xjc (xjc) on project my-project: 
[ERROR] +=================== [XJC Error]
[ERROR] |
[ERROR] | 0: file:/Path_to_my/my.dtd
[ERROR] |
[ERROR] +=================== [End XJC Error]

I checked the permissions of my.dtd, and it should be able to read it, I even changed them to all read, write and execute.

It still fails, any suggestions for OpenJDK 11 ?

**Comment by lennartj** [comment]
Updated all JAXB-API dependencies to the Jakarta artifacts (see #138), and got the full suite of IT tests to build on JDK 11 as well.

However, it implies that one adds the dependency below (since the javax.xml.bind is not in the JDK any longer): 

```xml
<dependency>
  <groupId>jakarta.xml.bind</groupId>
  <artifactId>jakarta.xml.bind-api</artifactId>
  <version>2.3.2</version>
</dependency>
```

**Comment by shavo007** [comment]
@edwardxia magic mate! such a minefield to get this plugin working with java 11. i just wanted to use schema gen...

**Comment by DhruvAShah** [comment]
Hi ,
I was getting similar compilation errors while building maven with Java 17 and maven-jaxb2 plugin 2.3.0 . I tried latest version as well but got Mojo Exception while building the same with Maven . After researching a bit I was able to fix the issue using below implementation for jaxb2-plugin ,

Java - 17
Jaxb2-maven-plugin - 0.14.0
Spring Boot Maven - 2.7.4

In properties Tag add below version ,
	<maven-jaxb2-plugin.version>0.14.0</maven-jaxb2-plugin.version>

In Build Tag , 
	<plugin>
               <groupId>org.jvnet.jaxb2.maven2</groupId>
               <artifactId>maven-jaxb2-plugin</artifactId>
               <version>${maven-jaxb2-plugin.version}</version>
               <executions>
                   <execution>
                       <id>example-xmls</id>
                       <goals>
                           <goal>generate</goal>
                       </goals>
                       <configuration>
                           <generateDirectory>${project.basedir}/src/main/java/com/cumulocity/exchnage_Demo</generateDirectory>
                           <schemaDirectory>${project.basedir}/src/main/resources/</schemaDirectory>
                           <schemaIncludes>
                               <include>**/*.xsd</include>
                           </schemaIncludes>
                           <bindingDirectory>${project.basedir}/src/main/resources/</bindingDirectory>
                           <bindingIncludes>
                               <include>**/*.xjb</include>
                           </bindingIncludes>
                       </configuration>
                   </execution>
               </executions>
               <dependencies>
                   <dependency>
                       <groupId>org.glassfish.jaxb</groupId>
                       <artifactId>jaxb-runtime</artifactId>
                       <version>2.3.3</version>
                   </dependency>
               </dependencies>
           	</plugin>	

After this JAXB-2 Implementation was successfully generated . Make sure to add below dependency as well helpful to provide implementation during runtime (When we run the main class)

	<dependency>
             <groupId>org.glassfish.jaxb</groupId>
             <artifactId>jaxb-runtime</artifactId>
             <version>2.3.3</version>
             <scope>runtime</scope>
        </dependency>

This should work for all those struggling with Java 17 and spring boot version 2.7.4 with jabxb2 maven plugin .

**Comment by MatBC234** [comment]
failed to execute mojo org.codehaus.mojo:jaxb2-maven-plugin:3.2.0:xjc {execution: generate-jaxb} (org.codehaus.mojo:jaxb2-maven-plugin:3.2.0:xjc:generate-jaxb:generate-sources) I'm getting this issue with Java 21, Maven 3.9.9, any way to fix it?

**Comment by slachiewicz** [comment]
Please share more details about error or minimal project to reproduce
